### ISSUE TITLE
MSWord: Fails to run basic test on Yoga

### ISSUE THREAD

**Issue by mcgeagh** [jimboatarm/workload-automation#112]
MSword workload fails, even when use_test_file is false.
Tested on Huawei Mate 8 = OK, and on Lenovo Yoga Tab 3 Pro = FAIL.

```
ERROR    Error while running workload:
ERROR           INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    com.arm.wlauto.uiauto.msword.UiAutomation:
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.msword.UiAutomation
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: 1
ERROR    INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Error in runUiAutomation:
ERROR    com.android.uiautomator.core.UiObjectNotFoundException: Could not find view with resource ID: com.microsoft.office.word:id/DocTitlePortrait
ERROR           at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByResourceId(BaseUiAutomation.java:443)
ERROR           at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:404)
ERROR           at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:387)
ERROR           at com.arm.wlauto.uiauto.msword.UiAutomation.testCreateDocument(UiAutomation.java:101)
ERROR           at com.arm.wlauto.uiauto.msword.UiAutomation.runUiAutomation(UiAutomation.java:83)
ERROR           at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR           at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR           at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR           at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR           at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR           at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
ERROR
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.msword.UiAutomation
ERROR    INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: Could not find view with resource ID: com.microsoft.office.word:id/DocTitlePortrait
ERROR           at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByResourceId(BaseUiAutomation.java:443)
ERROR           at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:404)
ERROR           at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:387)
ERROR           at com.arm.wlauto.uiauto.msword.UiAutomation.testCreateDocument(UiAutomation.java:101)
ERROR           at com.arm.wlauto.uiauto.msword.UiAutomation.runUiAutomation(UiAutomation.java:83)
ERROR           at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR           at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR           at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR           at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR           at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR           at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
ERROR
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Test results for WatcherResultPrinter=.E
ERROR    Time: 22.28
ERROR
ERROR    FAILURES!!!
ERROR    Tests run: 1,  Failures: 0,  Errors: 1
ERROR
ERROR
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR
```

![error](https://cloud.githubusercontent.com/assets/550606/16387267/0a245490-3c8c-11e6-8f80-01e966716b62.png)

**Comment by muendelezaji** [comment]
Related to #97
