### ISSUE TITLE
GooglePhotos: Fails on 'ELM' device

### ISSUE THREAD

**Issue by mcgeagh** [jimboatarm/workload-automation#125]
```
2016-07-08 13:42:27,192 ERROR    Runner: Error while running workload:
2016-07-08 13:42:27,192 ERROR    Runner:    INSTRUMENTATION_STATUS: numtests=1
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: stream=
2016-07-08 13:42:27,192 ERROR    Runner: com.arm.wlauto.uiauto.googlephotos.UiAutomation:
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: test=runUiAutomation
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.googlephotos.UiAutomation
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: current=1
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS_CODE: 1
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: numtests=1
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: stream=
2016-07-08 13:42:27,192 ERROR    Runner: Error in runUiAutomation:
2016-07-08 13:42:27,192 ERROR    Runner: com.android.uiautomator.core.UiObjectNotFoundException: Could not find "Navigate Up" "android.widget.ImageButton"
2016-07-08 13:42:27,192 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByDescription(BaseUiAutomation.java:427)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByDescription(BaseUiAutomation.java:420)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.arm.wlauto.uiauto.googlephotos.UiAutomation.gesturesTest(UiAutomation.java:161)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.arm.wlauto.uiauto.googlephotos.UiAutomation.runUiAutomation(UiAutomation.java:53)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
2016-07-08 13:42:27,192 ERROR    Runner: 
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: test=runUiAutomation
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.googlephotos.UiAutomation
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: Could not find "Navigate Up" "android.widget.ImageButton"
2016-07-08 13:42:27,192 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByDescription(BaseUiAutomation.java:427)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByDescription(BaseUiAutomation.java:420)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.arm.wlauto.uiauto.googlephotos.UiAutomation.gesturesTest(UiAutomation.java:161)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.arm.wlauto.uiauto.googlephotos.UiAutomation.runUiAutomation(UiAutomation.java:53)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
2016-07-08 13:42:27,192 ERROR    Runner:    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
2016-07-08 13:42:27,192 ERROR    Runner: 
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: current=1
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS_CODE: -1
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS: stream=
2016-07-08 13:42:27,192 ERROR    Runner: Test results for WatcherResultPrinter=.E
2016-07-08 13:42:27,192 ERROR    Runner: Time: 94.286
2016-07-08 13:42:27,192 ERROR    Runner: 
2016-07-08 13:42:27,192 ERROR    Runner: FAILURES!!!
2016-07-08 13:42:27,192 ERROR    Runner: Tests run: 1,  Failures: 0,  Errors: 1
2016-07-08 13:42:27,192 ERROR    Runner: 
2016-07-08 13:42:27,192 ERROR    Runner: 
2016-07-08 13:42:27,192 ERROR    Runner: INSTRUMENTATION_STATUS_CODE: -1
2016-07-08 13:42:27,192 ERROR    Runner: 
```

![error](https://cloud.githubusercontent.com/assets/550606/16688695/218f5f38-4517-11e6-98c9-f22d8ef0f7a4.png)

**Comment by mcgeagh** [comment]
```
<?xml version="1.0" ?>
<hierarchy rotation="0">
    <node bounds="[528,454][1392,626]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="android" password="false" resource-id="" scrollable="false" selected="false" text="">
        <node bounds="[544,470][1376,610]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="android" password="false" resource-id="" scrollable="false" selected="false" text="">
            <node bounds="[544,470][1376,610]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="android" password="false" resource-id="android:id/content" scrollable="false" selected="false" text="">
                <node bounds="[544,470][1376,610]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="android" password="false" resource-id="android:id/parentPanel" scrollable="false" selected="false" text="">
                    <node bounds="[544,470][1376,548]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="android" password="false" resource-id="android:id/contentPanel" scrollable="false" selected="false" text="">
                        <node bounds="[544,470][1376,548]" checkable="false" checked="false" class="android.widget.ScrollView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="android" password="false" resource-id="android:id/scrollView" scrollable="false" selected="false" text="">
                            <node bounds="[544,488][1376,548]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="android" password="false" resource-id="" scrollable="false" selected="false" text="">
                                <node bounds="[544,488][1376,548]" checkable="false" checked="false" class="android.widget.TextView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="android" password="false" resource-id="android:id/message" scrollable="false" selected="false" text="Photos isn't responding.

Do you want to close it?"/>
                            </node>
                        </node>
                    </node>
                    <node bounds="[544,548][1376,610]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="1" long-clickable="false" package="android" password="false" resource-id="android:id/buttonPanel" scrollable="false" selected="false" text="">
                        <node bounds="[1236,552][1300,606]" checkable="false" checked="false" class="android.widget.Button" clickable="true" content-desc="" enabled="true" focusable="true" focused="false" index="0" long-clickable="false" package="android" password="false" resource-id="android:id/button2" scrollable="false" selected="false" text="Wait"/>
                        <node bounds="[1300,552][1364,606]" checkable="false" checked="false" class="android.widget.Button" clickable="true" content-desc="" enabled="true" focusable="true" focused="false" index="1" long-clickable="false" package="android" password="false" resource-id="android:id/button1" scrollable="false" selected="false" text="OK"/>
                    </node>
                </node>
            </node>
        </node>
    </node>
</hierarchy>
```
