### ISSUE TITLE
Reader: Fails on 'ELM' device

### ISSUE THREAD

**Issue by mcgeagh** [jimboatarm/workload-automation#126]
```
2016-07-08 14:01:35,210 ERROR    Runner: Error while running workload:
2016-07-08 14:01:35,210 ERROR    Runner:    INSTRUMENTATION_STATUS: numtests=1
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: stream=
2016-07-08 14:01:35,210 ERROR    Runner: com.arm.wlauto.uiauto.reader.UiAutomation:
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: test=runUiAutomation
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.reader.UiAutomation
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: current=1
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS_CODE: 1
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: numtests=1
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: stream=
2016-07-08 14:01:35,210 ERROR    Runner: Error in runUiAutomation:
2016-07-08 14:01:35,210 ERROR    Runner: com.android.uiautomator.core.UiObjectNotFoundException: Could not find "cortex m4.pdf" "android.widget.TextView"
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByText(BaseUiAutomation.java:479)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByText(BaseUiAutomation.java:472)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.reader.UiAutomation.openFileFromList(UiAutomation.java:155)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.reader.UiAutomation.openFile(UiAutomation.java:107)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.reader.UiAutomation.gesturesTest(UiAutomation.java:184)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.reader.UiAutomation.runUiAutomation(UiAutomation.java:56)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
2016-07-08 14:01:35,210 ERROR    Runner: 
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: test=runUiAutomation
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.reader.UiAutomation
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: Could not find "cortex m4.pdf" "android.widget.TextView"
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByText(BaseUiAutomation.java:479)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByText(BaseUiAutomation.java:472)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.reader.UiAutomation.openFileFromList(UiAutomation.java:155)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.reader.UiAutomation.openFile(UiAutomation.java:107)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.reader.UiAutomation.gesturesTest(UiAutomation.java:184)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.arm.wlauto.uiauto.reader.UiAutomation.runUiAutomation(UiAutomation.java:56)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
2016-07-08 14:01:35,210 ERROR    Runner:    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
2016-07-08 14:01:35,210 ERROR    Runner: 
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: current=1
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS_CODE: -1
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS: stream=
2016-07-08 14:01:35,210 ERROR    Runner: Test results for WatcherResultPrinter=.E
2016-07-08 14:01:35,210 ERROR    Runner: Time: 16.299
2016-07-08 14:01:35,210 ERROR    Runner: 
2016-07-08 14:01:35,210 ERROR    Runner: FAILURES!!!
2016-07-08 14:01:35,210 ERROR    Runner: Tests run: 1,  Failures: 0,  Errors: 1
2016-07-08 14:01:35,210 ERROR    Runner: 
2016-07-08 14:01:35,210 ERROR    Runner: 
2016-07-08 14:01:35,210 ERROR    Runner: INSTRUMENTATION_STATUS_CODE: -1
2016-07-08 14:01:35,210 ERROR    Runner: 
```

![error](https://cloud.githubusercontent.com/assets/550606/16688859/ff027c38-4517-11e6-8122-c1ed79cea25d.png)

**Comment by mcgeagh** [comment]
```
<?xml version="1.0" ?>
<hierarchy rotation="0">
    <node bounds="[448,116][1472,916]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="" scrollable="false" selected="false" text="">
        <node bounds="[448,116][1472,916]" checkable="false" checked="false" class="android.support.v4.widget.DrawerLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/drawer_layout" scrollable="false" selected="false" text="">
            <node bounds="[448,116][1472,916]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/drawer_content" scrollable="false" selected="false" text="">
                <node bounds="[448,116][1472,916]" checkable="false" checked="false" class="android.widget.RelativeLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="" scrollable="false" selected="false" text="">
                    <node bounds="[448,116][1472,148]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/caption" scrollable="false" selected="false" text="">
                        <node bounds="[448,116][480,148]" checkable="false" checked="false" class="android.widget.ImageView" clickable="true" content-desc="Back" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/back_button" scrollable="false" selected="false" text=""/>
                        <node bounds="[1376,116][1408,148]" checkable="false" checked="false" class="android.widget.ImageView" clickable="true" content-desc="Minimize" enabled="true" focusable="false" focused="false" index="1" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/minimize_window" scrollable="false" selected="false" text=""/>
                        <node bounds="[1408,116][1440,148]" checkable="false" checked="false" class="android.widget.ImageView" clickable="true" content-desc="Maximize" enabled="true" focusable="false" focused="false" index="2" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/maximize_window" scrollable="false" selected="false" text=""/>
                        <node bounds="[1440,116][1472,148]" checkable="false" checked="false" class="android.widget.ImageView" clickable="true" content-desc="Close" enabled="true" focusable="false" focused="false" index="3" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/close_window" scrollable="false" selected="false" text=""/>
                    </node>
                    <node bounds="[448,148][1472,916]" checkable="false" checked="false" class="android.view.ViewGroup" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="1" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/decor_content_parent" scrollable="false" selected="false" text="">
                        <node bounds="[448,148][1472,208]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/action_bar_container" scrollable="false" selected="false" text="">
                            <node bounds="[448,148][1472,208]" checkable="false" checked="false" class="android.view.ViewGroup" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/action_bar" scrollable="false" selected="false" text="">
                                <node bounds="[448,148][474,208]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="true" content-desc="My Documents, Navigate up" enabled="true" focusable="true" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="" scrollable="false" selected="false" text="">
                                    <node bounds="[448,148][474,208]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="true" content-desc="Navigate up" enabled="true" focusable="true" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="" scrollable="false" selected="false" text="">
                                        <node bounds="[448,166][472,190]" checkable="false" checked="false" class="android.widget.ImageView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/up" scrollable="false" selected="false" text=""/>
                                        <node bounds="[469,178][470,179]" checkable="false" checked="false" class="android.widget.ImageView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="1" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/home" scrollable="false" selected="false" text=""/>
                                    </node>
                                </node>
                                <node bounds="[474,148][794,208]" checkable="false" checked="false" class="android.widget.SearchView" clickable="false" content-desc="" enabled="true" focusable="true" focused="false" index="1" long-clickable="false" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/split_pane_search" scrollable="false" selected="false" text="">
                                    <node bounds="[474,148][794,208]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/search_bar" scrollable="false" selected="false" text="">
                                        <node bounds="[482,159][786,197]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/search_edit_frame" scrollable="false" selected="false" text="">
                                            <node bounds="[482,159][786,197]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/search_plate" scrollable="false" selected="false" text="">
                                                <node bounds="[484,159][747,195]" checkable="false" checked="false" class="android.widget.EditText" clickable="true" content-desc="" enabled="true" focusable="true" focused="true" index="0" long-clickable="true" package="com.adobe.reader" password="false" resource-id="android:id/search_src_text" scrollable="false" selected="false" text="cortex m4.pdf"/>
                                                <node bounds="[747,159][784,195]" checkable="false" checked="false" class="android.widget.ImageView" clickable="true" content-desc="Clear query" enabled="true" focusable="true" focused="false" index="1" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/search_close_btn" scrollable="false" selected="false" text=""/>
                                            </node>
                                        </node>
                                    </node>
                                </node>
                            </node>
                        </node>
                        <node bounds="[448,208][1472,916]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="1" long-clickable="false" package="com.adobe.reader" password="false" resource-id="android:id/content" scrollable="false" selected="false" text="">
                            <node bounds="[448,208][1472,916]" checkable="false" checked="false" class="android.widget.RelativeLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/split_pane_layout" scrollable="false" selected="false" text="">
                                <node bounds="[448,208][1472,916]" checkable="false" checked="false" class="android.widget.RelativeLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/split_pane_main_container" scrollable="false" selected="false" text="">
                                    <node bounds="[448,208][1472,916]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="" scrollable="false" selected="false" text=""/>
                                    <node bounds="[448,208][1472,916]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="1" long-clickable="false" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/tabs_fragment" scrollable="false" selected="false" text="">
                                        <node bounds="[448,208][1472,916]" checkable="false" checked="false" class="android.support.v4.view.ViewPager" clickable="false" content-desc="" enabled="true" focusable="true" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/tabs_viewpager" scrollable="true" selected="false" text="">
                                            <node bounds="[448,208][1472,916]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="1" long-clickable="false" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/allPDFLayout" scrollable="false" selected="false" text="">
                                                <node bounds="[448,208][1472,916]" checkable="false" checked="false" class="android.view.ViewGroup" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/local_list_view_swipe_container" scrollable="false" selected="false" text="">
                                                    <node bounds="[448,208][1472,916]" checkable="false" checked="false" class="android.widget.ListView" clickable="true" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="true" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/local_document_list_view" scrollable="false" selected="false" text=""/>
                                                </node>
                                                <node bounds="[480,208][1440,916]" checkable="false" checked="false" class="android.widget.TextView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="1" long-clickable="false" package="com.adobe.reader" password="false" resource-id="com.adobe.reader:id/no_matching_local_files" scrollable="false" selected="false" text="No files were found"/>
                                            </node>
                                        </node>
                                    </node>
                                </node>
                            </node>
                        </node>
                    </node>
                </node>
            </node>
        </node>
    </node>
</hierarchy>

```
