### ISSUE TITLE
MSWord: Fails on 'ELM' device

### ISSUE THREAD

**Issue by mcgeagh** [jimboatarm/workload-automation#129]
```
2016-07-08 14:37:36,308 ERROR    Runner: Error while running workload:
2016-07-08 14:37:36,308 ERROR    Runner:    INSTRUMENTATION_STATUS: numtests=1
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: stream=
2016-07-08 14:37:36,308 ERROR    Runner: com.arm.wlauto.uiauto.msword.UiAutomation:
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: test=runUiAutomation
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.msword.UiAutomation
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: current=1
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS_CODE: 1
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: numtests=1
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: stream=
2016-07-08 14:37:36,308 ERROR    Runner: Error in runUiAutomation:
2016-07-08 14:37:36,308 ERROR    Runner: com.android.uiautomator.core.UiObjectNotFoundException: Could not find view with text: Show SD card
2016-07-08 14:37:36,308 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByText(BaseUiAutomation.java:489)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:413)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:387)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.arm.wlauto.uiauto.msword.UiAutomation.testExistingDocument(UiAutomation.java:276)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.arm.wlauto.uiauto.msword.UiAutomation.runUiAutomation(UiAutomation.java:81)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
2016-07-08 14:37:36,308 ERROR    Runner: 
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: test=runUiAutomation
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.msword.UiAutomation
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: Could not find view with text: Show SD card
2016-07-08 14:37:36,308 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByText(BaseUiAutomation.java:489)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:413)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.arm.wlauto.uiauto.BaseUiAutomation.clickUiObject(BaseUiAutomation.java:387)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.arm.wlauto.uiauto.msword.UiAutomation.testExistingDocument(UiAutomation.java:276)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.arm.wlauto.uiauto.msword.UiAutomation.runUiAutomation(UiAutomation.java:81)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
2016-07-08 14:37:36,308 ERROR    Runner:    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
2016-07-08 14:37:36,308 ERROR    Runner: 
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: current=1
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS_CODE: -1
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS: stream=
2016-07-08 14:37:36,308 ERROR    Runner: Test results for WatcherResultPrinter=.E
2016-07-08 14:37:36,308 ERROR    Runner: Time: 122.461
2016-07-08 14:37:36,308 ERROR    Runner: 
2016-07-08 14:37:36,308 ERROR    Runner: FAILURES!!!
2016-07-08 14:37:36,308 ERROR    Runner: Tests run: 1,  Failures: 0,  Errors: 1
2016-07-08 14:37:36,308 ERROR    Runner: 
2016-07-08 14:37:36,308 ERROR    Runner: 
2016-07-08 14:37:36,308 ERROR    Runner: INSTRUMENTATION_STATUS_CODE: -1
2016-07-08 14:37:36,308 ERROR    Runner: 
```

![error](https://cloud.githubusercontent.com/assets/550606/16689281/2704f3e4-451a-11e6-8098-8f02ca9394c2.png)

**Comment by mcgeagh** [comment]
```
<?xml version="1.0" ?>
<hierarchy rotation="0">
    <node bounds="[1171,194][1367,290]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.android.documentsui" password="false" resource-id="" scrollable="false" selected="false" text="">
        <node bounds="[1171,194][1367,290]" checkable="false" checked="false" class="android.widget.FrameLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.android.documentsui" password="false" resource-id="" scrollable="false" selected="false" text="">
            <node bounds="[1171,194][1367,290]" checkable="false" checked="false" class="android.widget.ListView" clickable="true" content-desc="" enabled="true" focusable="true" focused="true" index="0" long-clickable="false" package="com.android.documentsui" password="false" resource-id="" scrollable="false" selected="false" text="">
                <node bounds="[1171,194][1367,242]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="true" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.android.documentsui" password="false" resource-id="" scrollable="false" selected="false" text="">
                    <node bounds="[1187,207][1351,229]" checkable="false" checked="false" class="android.widget.RelativeLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.android.documentsui" password="false" resource-id="" scrollable="false" selected="false" text="">
                        <node bounds="[1187,207][1351,229]" checkable="false" checked="false" class="android.widget.TextView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.android.documentsui" password="false" resource-id="android:id/title" scrollable="false" selected="false" text="Show internal storage"/>
                    </node>
                </node>
                <node bounds="[1171,242][1367,290]" checkable="false" checked="false" class="android.widget.LinearLayout" clickable="true" content-desc="" enabled="true" focusable="false" focused="false" index="1" long-clickable="false" package="com.android.documentsui" password="false" resource-id="" scrollable="false" selected="false" text="">
                    <node bounds="[1187,255][1351,277]" checkable="false" checked="false" class="android.widget.RelativeLayout" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.android.documentsui" password="false" resource-id="" scrollable="false" selected="false" text="">
                        <node bounds="[1187,255][1351,277]" checkable="false" checked="false" class="android.widget.TextView" clickable="false" content-desc="" enabled="true" focusable="false" focused="false" index="0" long-clickable="false" package="com.android.documentsui" password="false" resource-id="android:id/title" scrollable="false" selected="false" text="Show file size"/>
                    </node>
                </node>
            </node>
        </node>
    </node>
</hierarchy>

```
