### ISSUE TITLE
multiapp crashes in photos looking for the wa-working folder (1st iteration)

### ISSUE THREAD

**Issue by jimboatarm** [jimboatarm/workload-automation#43]
So far this has only happened on the first iteration:

INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing
INFO     Running workloads
INFO     Connecting to device
INFO     Initializing device
INFO     Initializing workloads
INFO     Running workload 1 multiapp (iteration 1)
INFO        Setting up
INFO     Installing dependency Gmail
INFO     Installing dependency Skype
INFO        Executing
ERROR    Error while running workload:
ERROR       INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    com.arm.wlauto.uiauto.multiapp.UiAutomation:
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.multiapp.UiAutomation
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: 1
ERROR    INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Error in runUiAutomation:
ERROR    com.android.uiautomator.core.UiObjectNotFoundException: UiObject is not found: UiSelector[TEXT=wa-working]
ERROR       at com.arm.wlauto.uiauto.BaseUiAutomation.waitObject(BaseUiAutomation.java:82)
ERROR       at com.arm.wlauto.uiauto.googlephotos.UiAutomation.dismissWelcomeView(UiAutomation.java:101)
ERROR       at com.arm.wlauto.uiauto.multiapp.UiAutomation.runUiAutomation(UiAutomation.java:30)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR       at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR       at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
ERROR  
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.multiapp.UiAutomation
ERROR    INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: UiObject is not found: UiSelector[TEXT=wa-working]
ERROR       at com.arm.wlauto.uiauto.BaseUiAutomation.waitObject(BaseUiAutomation.java:82)
ERROR       at com.arm.wlauto.uiauto.googlephotos.UiAutomation.dismissWelcomeView(UiAutomation.java:101)
ERROR       at com.arm.wlauto.uiauto.multiapp.UiAutomation.runUiAutomation(UiAutomation.java:30)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR       at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR       at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
ERROR  
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Test results for WatcherResultPrinter=.E
ERROR    Time: 26.375
ERROR  
ERROR    FAILURES!!!
ERROR    Tests run: 1,  Failures: 0,  Errors: 1
ERROR  
ERROR  
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR  
INFO        Processing result
INFO        Tearing down

**Comment by jimboatarm** [comment]
Resolved by fixes to other workloads and creating a suitable agenda.
