### ISSUE TITLE
multiapp crashes in gmail after sending the mail (2nd iteration onwards)

### ISSUE THREAD

**Issue by jimboatarm** [jimboatarm/workload-automation#44]
INFO     Running workload 1 multiapp (iteration 2)
INFO        Setting up
INFO     Installing dependency Gmail
INFO     Installing dependency Skype
INFO        Executing
ERROR    Error while running workload:
ERROR       INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    com.arm.wlauto.uiauto.multiapp.UiAutomation:
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.multiapp.UiAutomation
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: 1
ERROR    INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Error in runUiAutomation:
ERROR    com.android.uiautomator.core.UiObjectNotFoundException: UiSelector[CHILD=UiSelector[INDEX=1], RESOURCE_ID=com.google.android.apps.photos:id/recycler_view]
ERROR       at com.android.uiautomator.core.UiObject.getBounds(UiObject.java:831)
ERROR       at com.arm.wlauto.uiauto.BaseUiAutomation.uiDevicePerformLongClick(BaseUiAutomation.java:284)
ERROR       at com.arm.wlauto.uiauto.googlephotos.UiAutomation.tagPhoto(UiAutomation.java:424)
ERROR       at com.arm.wlauto.uiauto.multiapp.UiAutomation.runUiAutomation(UiAutomation.java:37)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR       at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR       at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
ERROR  
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.multiapp.UiAutomation
ERROR    INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: UiSelector[CHILD=UiSelector[INDEX=1], RESOURCE_ID=com.google.android.apps.photos:id/recycler_view]
ERROR       at com.android.uiautomator.core.UiObject.getBounds(UiObject.java:831)
ERROR       at com.arm.wlauto.uiauto.BaseUiAutomation.uiDevicePerformLongClick(BaseUiAutomation.java:284)
ERROR       at com.arm.wlauto.uiauto.googlephotos.UiAutomation.tagPhoto(UiAutomation.java:424)
ERROR       at com.arm.wlauto.uiauto.multiapp.UiAutomation.runUiAutomation(UiAutomation.java:37)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR       at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR       at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
ERROR  
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Test results for WatcherResultPrinter=.E
ERROR    Time: 60.462
ERROR  
ERROR    FAILURES!!!
ERROR    Tests run: 1,  Failures: 0,  Errors: 1
ERROR  
ERROR  
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR  
INFO        Processing result
INFO        Tearing down
INFO     Job status was FAILED. Retrying...

**Comment by jimboatarm** [comment]
Appears to have gone away.  10 iterations tested last week with no issues.
