### ISSUE TITLE
multiapp: accidentally launches Google Now instead of Gmail when sending a photo from Google Photos

### ISSUE THREAD

**Issue by mcgeagh** [jimboatarm/workload-automation#81]
Happens on the Lenovo Yoga Tab 3 Pro. Does not happen on the Huawei Mate 8
1. Google Photos launches
2. Welcome screen dismissed
3. Image selected
4. List of apps to send it to appears at the bottom
5. Google Now circle appears. UIAutomator clicks the Google Circle and this Launches Google Now

![error](https://cloud.githubusercontent.com/assets/550606/16122287/699bec96-33de-11e6-9d4e-43820d0936cd.png)

```
INFO     Running workload 1 multiapp (iteration 4)
INFO            Setting up
INFO     Checking dependency Gmail
INFO     Checking dependency Skype
INFO            Executing
ERROR    Error while running workload:
ERROR           INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    com.arm.wlauto.uiauto.multiapp.UiAutomation:
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.multiapp.UiAutomation
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: 1
ERROR    INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Error in runUiAutomation:
ERROR    com.android.uiautomator.core.UiObjectNotFoundException: UiSelector[RESOURCE_ID=com.google.android.apps.photos:id/application_grid]
ERROR           at com.android.uiautomator.core.UiScrollable.scrollForward(UiScrollable.java:416)
ERROR           at com.android.uiautomator.core.UiScrollable.scrollForward(UiScrollable.java:397)
ERROR           at com.arm.wlauto.uiauto.multiapp.UiAutomation.shareUsingApp(UiAutomation.java:126)
ERROR           at com.arm.wlauto.uiauto.multiapp.UiAutomation.sendToGmail(UiAutomation.java:58)
ERROR           at com.arm.wlauto.uiauto.multiapp.UiAutomation.runUiAutomation(UiAutomation.java:37)
ERROR           at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR           at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR           at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR           at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR           at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR           at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
ERROR
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.multiapp.UiAutomation
ERROR    INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: UiSelector[RESOURCE_ID=com.google.android.apps.photos:id/application_grid]
ERROR           at com.android.uiautomator.core.UiScrollable.scrollForward(UiScrollable.java:416)
ERROR           at com.android.uiautomator.core.UiScrollable.scrollForward(UiScrollable.java:397)
ERROR           at com.arm.wlauto.uiauto.multiapp.UiAutomation.shareUsingApp(UiAutomation.java:126)
ERROR           at com.arm.wlauto.uiauto.multiapp.UiAutomation.sendToGmail(UiAutomation.java:58)
ERROR           at com.arm.wlauto.uiauto.multiapp.UiAutomation.runUiAutomation(UiAutomation.java:37)
ERROR           at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR           at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR           at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR           at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR           at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR           at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
ERROR
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Test results for WatcherResultPrinter=.E
ERROR    Time: 32.333
ERROR
ERROR    FAILURES!!!
ERROR    Tests run: 1,  Failures: 0,  Errors: 1
ERROR
ERROR
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR
INFO            Processing result
INFO            Tearing down
```

**Comment by johnrchrdsn** [comment]
Could you try selecting the `applicationGrid` UiObject using the class name `android.support.v7.widget.RecyclerView` instead of by `resourceId`.

Or if that doesn't work selecting based on the criteria that the UiObject should be `focused` and `focusable`. i.e. that both of those properties are set to `true`.

Hopefully one of those selection criteria should be unique and uniform across devices.
